# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20160724_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='phone',
        ),
    ]
