# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_legal_entity', models.CharField(max_length=250)),
                ('pan_number', models.CharField(max_length=20)),
                ('registered_office_address', models.CharField(max_length=200)),
                ('name_of_store', models.CharField(max_length=100)),
                ('store_contact_number', models.PositiveIntegerField(blank=True, null=True)),
                ('store_long', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('store_lat', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('store_start_time', models.DateTimeField()),
                ('store_end_time', models.DateTimeField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant')),
            ],
        ),
    ]
