# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160721_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecategory',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='store_categories',
            field=models.ManyToManyField(blank=True, to='stores.StoreCategory'),
        ),
    ]
