# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20160721_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='store_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.StoreCategory'),
        ),
    ]
