# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20160721_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store'},
        ),
        migrations.AlterModelOptions(
            name='storecategory',
            options={'verbose_name': 'Store Category', 'verbose_name_plural': 'Store Categories'},
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='store_category',
            field=models.CharField(choices=[(0, 'Grocery'), (1, 'Meats'), (2, 'Sports'), (3, 'Foods'), (4, 'Bags')], default=0, max_length=10),
        ),
    ]
