# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20160722_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='store_category',
            field=models.CharField(choices=[('GROCERY', 'Grocery'), ('MEATS', 'Meats'), ('SPORTS', 'Sports'), ('FOODS', 'Foods'), ('BAGS', 'Bags')], default='GROCERY', max_length=10),
        ),
    ]
