# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 09:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20160722_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_off_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Sat', max_length=3),
        ),
    ]
