# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_store_off_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_categories',
        ),
        migrations.AddField(
            model_name='storecategory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_category', to='stores.Product'),
        ),
    ]
