# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 06:34
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20160724_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_off_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Sat', max_length=7),
        ),
    ]
