# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20160724_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_start_time',
            field=models.TimeField(),
        ),
    ]
