# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20160727_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
