# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20160801_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Product'),
        ),
    ]
